# Generated by Django 4.2.3 on 2023-07-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_basket_ingredient_alter_basket_recipe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="measurement_unit",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
