# Generated by Django 4.2.3 on 2023-07-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_basket_options_alter_favorites_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="api.recipes",
            ),
        ),
    ]
