# Generated by Django 4.2.3 on 2023-07-28 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorites",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
